# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder ".", "/vagrant_data"
  config.vm.synched_folder "../local_server/plugins", "/server/plugins"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get remove -y --purge man-db
    apt-get upgrade
    apt-get install -y default-jre

    mkdir /server
    chown vagrant:vagrant -R /server # Necessary for minecraft to make new sub directories.
    cd /server

    cp -r /vagrant_data/server_files/* .
    
    cp -r /vagrant_data/minecraft.service /etc/systemd/system
    systemctl enable minecraft.service
    systemctl start minecraft.service

    # https://www.youtube.com/watch?v=dC-hecmyxr4&ab_channel=ForeverJonny
    snap install ngrok # NGROK allows anyone to join the server if they have the link
    ngrok authtoken 1r876itpaXZWHSQFbT8qLeDkbbS_adj4zYJZuGfyYtFGYTtX
    ngrok tcp -region us 25565 &
    sleep 3
    curl http://127.0.0.1:4040/api/tunnels
    
  SHELL
end
